services:
  mongodb:
    image: mongo:7-jammy
    container_name: rag_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=rag
    networks:
      - rag_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      # Only keep data volumes, not source code
      - uploaded_docs:/app/uploaded_docs
      - app_logs:/app/logs
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=rag
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PROJECT_NAME=Document RAG API
      - UPLOAD_DIR=/app/uploaded_docs
      - PYTHONPATH=/app
    networks:
      - rag_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: rag_frontend
    restart: unless-stopped
    ports:
      - "7860:7860"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - API_URL=http://backend:8000
    networks:
      - rag_network

volumes:
  mongodb_data:
    driver: local
  uploaded_docs:
    driver: local
  app_logs:
    driver: local

networks:
  rag_network:
    driver: bridge
